version: "3.9"

services:
  backend:
    build: ./backend
    container_name: codenotes-backend
    command: yarn start:dev   # modo desarrollo con hot reload
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: codenotes-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: codenotes-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:

